################################################################################
# Makefile for installing dotfiles
################################################################################

.PHONY: all
all: install

.PHONY: install
install: install.sh
	./install.sh

.PHONY: clean
clean: clean.sh
	./clean.sh

.PHONY: restore
restore: restore.sh
	./restore.sh
