################################################################################
# Makefile for installing dotfiles
################################################################################

all: install

install: install.sh
	./install.sh

clean: clean.sh
	./clean.sh

restore: restore.sh
	./restore.sh
