################################################################################
# Makefile for installing editor settings
################################################################################

.PHONY: all
all: editors

.PHONY: editors
editors: pycharm.sh sublime.sh
	./pycharm.sh
	./sublime.sh
