################################################################################
# Makefile for setting up a lisp development environment
################################################################################

.PHONY: all
all: sbcl quicklisp expokit

.PHONY: sbcl
sbcl: sbcl.sh
	./sbcl.sh

.PHONY: quicklisp
quicklisp: quicklisp.sh
	./quicklisp.sh

.PHONY: expokit
expokit: expokit.sh
	./expokit.sh
