################################################################################
# Makefile for setting up a lisp development environment
################################################################################

all: sbcl quicklisp expokit

sbcl: sbcl.sh
	./sbcl.sh

quicklisp: quicklisp.sh
	./quicklisp.sh

expokit: expokit.sh
	./expokit.sh
