################################################################################
# Makefile for setting up a python development environment
################################################################################

.PHONY: all
all: pyenv.sh
	./pyenv.sh
